Now the messages are colorized

diff --git a/install/install b/install/install
--- a/install/install
+++ b/install/install
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+source "$(dirname "$0")/messages"
+
 ############################################################
 # Header
 
@@ -23,7 +25,7 @@ environment_file="../.env"
 
 # If file exists and has not zero size
 if [ -s "$environment_file" ] ; then
-	>&2 echo "It seems like the environment file was already configured. If you would like to start from a fresh installation, please run ./uninstall first"
+	>&2 echo -e "${error} It seems like the environment file was already configured. If you would like to start from a fresh installation, please run ./uninstall first"
 	exit 1
 fi
 
@@ -35,13 +37,13 @@ fi
 dependencies=("node" "psql")
 for arg in ${dependencies[@]} ; do
 	if [ -z $(which "$arg") ] ; then
-		>&2 echo "You have unmet dependencies. Please install $arg before proceding with database installation."
+		>&2 echo -e "${error} You have unmet dependencies. Please install $arg before proceding with database installation."
 		exit 1
 	fi
-	>&2 echo "$arg ... CHECK"
+	>&2 echo -e "$arg ... ${check}"
 done
 
->&2 echo "All dependencies were met successfully"
+>&2 echo -e "\n${success} All dependencies were met successfully"
 
 ############################################################
 # Configuring PSQL
@@ -65,6 +67,8 @@ psql -c "CREATE USER $uname WITH ENCRYPTED PASSWORD '$passwd'; " \
 EOF
 
 >&2 echo -e "\nStarting database...\n"
+
+>&2 printf "${success} "
 
 cat << EOF
 You can now log in to psql with the command:
@@ -98,4 +102,4 @@ for sql_file in *.sql ; do
         -p "$port" -f "$sql_file"
 done
 
->&2 echo "Done."
+>&2 echo -e "${done}"
diff --git a/install/uninstall b/install/uninstall
--- a/install/uninstall
+++ b/install/uninstall
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+source "$(dirname "$0")/messages"
+
 print_header="$(dirname "$0")/header_creator/short_header"
 >&2 $print_header
 
@@ -10,7 +12,7 @@ uname="${database}_admin"
 
 environment_file="../.env"
 if [ ! -s "$environment_file" ] ; then
-	>&2 echo "There is no environment file. Have you installed properly?"
+	>&2 echo -e "${error} There is no environment file. Have you installed properly?"
 	exit 1
 fi
 
@@ -24,3 +26,4 @@ psql -c "DROP DATABASE $database; " \
 EOF
 
 rm "$environment_file"
+echo -e "${done}"
